In [328]:
from pathlib import Path
import pandas as pd
import numpy as np
from scipy import sparse
from datetime import datetime
import random

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader,TensorDataset

In [329]:
##try to append files
df_train = pd.read_csv("/Users/surbhiprasad/Advanced_ML/Kaggle_Competition/kaggle-the-rating-seekers/training.csv")

In [330]:
df_train.head()

   user_id  item_id  context_feature_id
0        0    28366                   2
1        0    16109                   2
2        0    11500                   3
3        0    20750                   2
4        0     8759                   2

In [331]:
df_train.shape

(970245, 3)

In [332]:
df_train=df_train.drop_duplicates() ##why?/

In [333]:
df_train.shape

(892371, 3)

In [334]:
df_train = df_train.sample(frac=1).reset_index(drop=True) ##shufffle

In [335]:
df_train.head()

   user_id  item_id  context_feature_id
0     9974    27644                   2
1    80354    28735                   2
2   105125     1092                   1
3    47143    18484                   2
4    61416    10009                   1

In [336]:
#df_train=df_train.groupby(['user_id','item_id']).size().reset_index().rename(columns={0:'count'})[['user_id','item_id']]

In [337]:
users=df_train['user_id'].unique()
items=df_train['item_id'].unique()

In [338]:
#users = np.append(users, 300000)

In [339]:
#items = np.append(items, 40000)

In [340]:
max(users)

200152

In [341]:
df_train

        user_id  item_id  context_feature_id
0          9974    27644                   2
1         80354    28735                   2
2        105125     1092                   1
3         47143    18484                   2
4         61416    10009                   1
...         ...      ...                 ...
892366   128045    34572                   1
892367   101190    17281                   2
892368   134604    27007                   2
892369   161938    39104                   1
892370    16162    16136                   2

[892371 rows x 3 columns]

In [342]:
user_id=list(users)[0]

In [345]:
final=[]
for i,user_id in enumerate(list(users)):
    if i%1000==0:
        print(i)
    one_user_data=df_train[df_train['user_id'] == user_id] 
    item_already=set(one_user_data['item_id'].unique())
    filtered = set(items).difference(item_already)
    np.random.seed(3)
    neg_samples=random.sample(list(filtered), len(one_user_data['item_id']))
    user_new=[user_id for k in range(len(neg_samples))]
    context=np.append(one_user_data['context_feature_id'],one_user_data['context_feature_id'])
    check=[(i,j,k) for i,j,k in zip(user_new,neg_samples,context)]
    final.append(check)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000

In [323]:
os.system('say "your program has finished"')

0

In [324]:
len(users)

169698

In [347]:
 
final = [item for sublist in final for item in sublist]

In [349]:
final

[(9974, 10130, 2),
 (9974, 28352, 2),
 (9974, 6218, 2),
 (9974, 37310, 2),
 (9974, 6731, 2),
 (9974, 12821, 2),
 (9974, 32418, 3),
 (9974, 22485, 2),
 (80354, 1664, 2),
 (80354, 21954, 3),
 (80354, 17311, 2),
 (80354, 3242, 2),
 (80354, 25347, 2),
 (80354, 35284, 2),
 (105125, 36984, 1),
 (105125, 30724, 1),
 (105125, 37470, 1),
 (105125, 1113, 1),
 (105125, 36979, 1),
 (47143, 7909, 2),
 (47143, 26448, 1),
 (47143, 17252, 1),
 (47143, 21480, 1),
 (47143, 18110, 1),
 (47143, 36520, 1),
 (47143, 38143, 1),
 (47143, 37629, 3),
 (47143, 14654, 1),
 (47143, 22834, 1),
 (47143, 33951, 1),
 (61416, 38927, 1),
 (61416, 23108, 1),
 (61416, 27716, 1),
 (61416, 5141, 1),
 (61416, 491, 2),
 (36889, 32974, 2),
 (36889, 37111, 2),
 (36889, 15744, 2),
 (36889, 34772, 2),
 (36889, 30374, 2),
 (169499, 20492, 2),
 (169499, 24703, 2),
 (169499, 25205, 2),
 (169499, 20340, 1),
 (169499, 27920, 2),
 (169499, 11096, 2),
 (169499, 20210, 2),
 (169499, 11387, 3),
 (106272, 33168, 2),
 (106272, 5340, 2),
 (106272, 19269, 2),
 (106272, 23224, 1),
 (106272, 39107, 2),
 (149231, 32395, 2),
 (149231, 22297, 2),
 (149231, 28005, 2),
 (149231, 16776, 2),
 (92122, 35068, 2),
 (92122, 5102, 1),
 (92122, 932, 2),
 (92122, 27328, 1),
 (92122, 4139, 1),
 (92122, 16437, 2),
 (39012, 52, 2),
 (39012, 35849, 2),
 (39012, 7989, 2),
 (39012, 17844, 3),
 (132242, 7389, 1),
 (132242, 29892, 1),
 (132242, 4969, 1),
 (132242, 12081, 1),
 (132242, 11938, 1),
 (132242, 2093, 1),
 (132242, 27763, 1),
 (132242, 7675, 1),
 (80538, 28708, 2),
 (80538, 15681, 3),
 (80538, 21247, 2),
 (80538, 790, 2),
 (118059, 17748, 1),
 (118059, 9634, 1),
 (118059, 25021, 1),
 (118059, 12911, 1),
 (118059, 26251, 1),
 (118059, 11682, 1),
 (118059, 11444, 1),
 (6521, 38914, 2),
 (6521, 17993, 2),
 (6521, 35545, 2),
 (6521, 21822, 3),
 (6521, 36867, 2),
 (6521, 27201, 2),
 (6521, 6314, 2),
 (6521, 29337, 3),
 (6521, 23028, 3),
 (6521, 35623, 2),
 (134023, 36869, 0),
 (134023, 2840, 2),
 (134023, 15521, 2),
 (134023, 1113, 2),
 (139663, 30441, 1),
 (139663, 21158, 1),
 (139663, 9801, 1),
 (139663, 31161, 2),
 (139663, 9862, 1),
 (139663, 22599, 1),
 (139663, 1960, 2),
 (185742, 35139, 0),
 (185742, 23989, 0),
 (185742, 24357, 0),
 (185742, 8491, 0),
 (185742, 8870, 0),
 (185742, 32496, 0),
 (10834, 19592, 2),
 (10834, 29584, 2),
 (10834, 13958, 2),
 (10834, 30725, 3),
 (10834, 2121, 2),
 (10834, 10521, 2),
 (10834, 14636, 3),
 (10834, 20566, 2),
 (73367, 28431, 1),
 (73367, 18853, 1),
 (73367, 39553, 1),
 (73367, 10601, 1),
 (73367, 39426, 1),
 (73367, 10761, 1),
 (73367, 13038, 2),
 (73367, 18782, 1),
 (125737, 8449, 2),
 (125737, 30573, 2),
 (125737, 1439, 2),
 (125737, 29210, 2),
 (116997, 16537, 3),
 (116997, 36986, 1),
 (1767, 15384, 2),
 (1767, 23914, 3),
 (1767, 23070, 2),
 (1767, 17147, 2),
 (1767, 32890, 2),
 (1767, 23581, 2),
 (1767, 8416, 2),
 (1767, 17132, 2),
 (1767, 19765, 2),
 (1767, 31952, 2),
 (28596, 9825, 1),
 (28596, 4597, 2),
 (28596, 7779, 1),
 (28596, 34768, 1),
 (28596, 16592, 1),
 (41870, 21255, 3),
 (41870, 747, 3),
 (41870, 20342, 2),
 (41870, 12898, 2),
 (41870, 38663, 2),
 (41870, 23699, 2),
 (41870, 6251, 2),
 (41870, 31030, 2),
 (41870, 28856, 2),
 (41870, 18022, 2),
 (41870, 14553, 3),
 (41870, 6221, 2),
 (41870, 9994, 2),
 (41870, 26703, 3),
 (41870, 33964, 3),
 (198543, 5048, 1),
 (198543, 33990, 0),
 (198543, 28018, 1),
 (198543, 11616, 0),
 (64868, 16952, 2),
 (64868, 16093, 2),
 (64868, 19984, 3),
 (64868, 14891, 2),
 (64868, 34922, 2),
 (64868, 23951, 2),
 (64868, 18604, 2),
 (64868, 8581, 3),
 (67241, 8651, 2),
 (67241, 8771, 3),
 (67241, 6271, 3),
 (67241, 13873, 3),
 (67241, 1688, 2),
 (67241, 20497, 2),
 (101844, 22648, 2),
 (101844, 7637, 2),
 (101844, 329, 2),
 (101844, 39041, 2),
 (101844, 17038, 3),
 (101844, 29699, 2),
 (129822, 16777, 2),
 (129822, 9547, 3),
 (129822, 37468, 2),
 (153642, 1469, 2),
 (153642, 33145, 2),
 (153642, 31084, 2),
 (153642, 37041, 2),
 (153642, 7150, 2),
 (143151, 11176, 1),
 (143151, 4987, 2),
 (143151, 15909, 2),
 (143151, 654, 3),
 (143151, 32550, 2),
 (143151, 30761, 3),
 (143151, 33147, 2),
 (143151, 18062, 2),
 (143151, 11581, 2),
 (143151, 11774, 1),
 (143151, 18876, 2),
 (143151, 9375, 2),
 (154293, 3451, 2),
 (154293, 20386, 2),
 (154293, 9585, 2),
 (154293, 215, 2),
 (154293, 10172, 2),
 (154293, 24876, 3),
 (154293, 22061, 3),
 (154293, 7571, 3),
 (136146, 19689, 1),
 (136146, 14852, 3),
 (136146, 26352, 2),
 (123390, 26726, 2),
 (123390, 35453, 2),
 (123390, 26546, 2),
 (123390, 32908, 3),
 (123390, 9428, 2),
 (123390, 1149, 2),
 (123390, 33415, 2),
 (123390, 33510, 1),
 (75536, 27705, 2),
 (75536, 37691, 1),
 (75536, 20442, 1),
 (75536, 34884, 2),
 (57977, 37526, 2),
 (57977, 36355, 2),
 (57977, 17945, 3),
 (57977, 25396, 2),
 (57977, 9917, 1),
 (57977, 21436, 1),
 (57977, 22944, 2),
 (57977, 30021, 1),
 (57977, 32766, 2),
 (184447, 36252, 3),
 (184447, 32236, 2),
 (184447, 38787, 2),
 (184447, 33885, 2),
 (184447, 9082, 3),
 (184447, 2377, 2),
 (184447, 6454, 2),
 (184447, 26713, 2),
 (184447, 713, 2),
 (184447, 13834, 2),
 (184447, 5660, 2),
 (184447, 32558, 3),
 (184447, 10023, 3),
 (184447, 17729, 2),
 (187960, 1946, 2),
 (187960, 5930, 2),
 (187960, 27860, 3),
 (187960, 37836, 3),
 (187960, 34613, 1),
 (88305, 10808, 1),
 (88305, 25602, 1),
 (88305, 313, 1),
 (88305, 6297, 1),
 (88305, 2909, 1),
 (88305, 15964, 1),
 (88305, 28333, 1),
 (88305, 19860, 1),
 (88305, 21487, 1),
 (88305, 9894, 1),
 (88305, 37038, 1),
 (88305, 25861, 1),
 (88305, 9817, 1),
 (88305, 37158, 1),
 (88305, 28330, 1),
 (88305, 7579, 1),
 (88305, 3103, 1),
 (127989, 28490, 2),
 (127989, 24906, 2),
 (127989, 7272, 2),
 (127989, 18685, 2),
 (27906, 31154, 2),
 (27906, 24236, 2),
 (27906, 23861, 2),
 (27906, 103, 2),
 (27906, 593, 2),
 (27906, 15102, 2),
 (27906, 19789, 2),
 (27906, 25740, 3),
 (27906, 6498, 2),
 (38445, 26540, 2),
 (38445, 25189, 2),
 (38445, 5765, 2),
 (38445, 16887, 3),
 (38445, 3500, 2),
 (38445, 33754, 3),
 (38445, 25285, 2),
 (38445, 7059, 2),
 (38445, 29398, 2),
 (38445, 23094, 2),
 (38445, 34209, 2),
 (38445, 29712, 3),
 (38445, 829, 2),
 (38445, 35698, 3),
 (38445, 84, 2),
 (170385, 29117, 1),
 (170385, 28431, 1),
 (170385, 24696, 1),
 (170385, 26247, 1),
 (170385, 39345, 1),
 (99363, 1735, 2),
 (99363, 23735, 2),
 (99363, 31997, 2),
 (99363, 10649, 2),
 (99363, 22013, 2),
 (45563, 9055, 0),
 (45563, 29107, 2),
 (45563, 24848, 2),
 (45563, 9639, 2),
 (45563, 36867, 2),
 (199650, 2604, 2),
 (199650, 7139, 1),
 (199650, 1593, 3),
 (199650, 13438, 3),
 (199650, 9973, 2),
 (199650, 22655, 3),
 (199650, 4961, 2),
 (199650, 24914, 2),
 (199650, 15752, 2),
 (199650, 836, 2),
 (199650, 32374, 2),
 (199650, 19627, 2),
 (67538, 23920, 3),
 (67538, 2581, 3),
 (67538, 6673, 2),
 (67538, 6553, 2),
 (173652, 35799, 2),
 (173652, 36088, 2),
 (173652, 19378, 2),
 (173652, 21703, 2),
 (84401, 12092, 1),
 (84401, 32631, 1),
 (84401, 35237, 1),
 (151068, 10728, 2),
 (151068, 10059, 2),
 (151068, 29553, 1),
 (151068, 8729, 2),
 (151068, 10609, 2),
 (151068, 22269, 3),
 (151068, 10499, 1),
 (151068, 38151, 1),
 (151068, 18666, 1),
 (14365, 21368, 1),
 (14365, 26690, 1),
 (14365, 9243, 1),
 (14365, 15227, 1),
 (14365, 10910, 1),
 (14365, 37346, 1),
 (14365, 14711, 1),
 (14365, 11019, 1),
 (14365, 37246, 1),
 (14365, 7160, 1),
 (14365, 18117, 1),
 (14365, 34962, 1),
 (109396, 26226, 3),
 (109396, 21525, 2),
 (109396, 33103, 2),
 (109396, 32477, 2),
 (109396, 23570, 2),
 (109396, 32290, 2),
 (109396, 8551, 2),
 (109396, 16091, 2),
 (109396, 37251, 2),
 (109396, 28798, 2),
 (109396, 11278, 2),
 (109396, 10740, 3),
 (109396, 16984, 2),
 (109396, 29800, 3),
 (109396, 16394, 2),
 (29150, 22424, 2),
 (29150, 10056, 3),
 (29150, 30934, 2),
 (29150, 34312, 3),
 (41448, 14765, 2),
 (41448, 24070, 2),
 (41448, 6948, 3),
 (41448, 20087, 3),
 (41448, 32927, 2),
 (41448, 21621, 2),
 (41448, 31947, 2),
 (41448, 12399, 2),
 (41448, 35469, 3),
 (41448, 10606, 3),
 (198756, 9529, 2),
 (198756, 28718, 2),
 (198756, 6482, 3),
 (198756, 3675, 2),
 (198756, 30514, 2),
 (198756, 10094, 3),
 (198756, 38660, 3),
 (198756, 24456, 2),
 (198756, 30362, 2),
 (100255, 26264, 2),
 (100255, 14217, 0),
 (100255, 3374, 0),
 (100255, 8383, 2),
 (100255, 39790, 2),
 (100255, 597, 2),
 (100255, 32365, 2),
 (100255, 9270, 2),
 (100255, 13919, 2),
 (176896, 38078, 2),
 (176896, 28613, 3),
 (176896, 12809, 2),
 (176896, 8592, 3),
 (176896, 26868, 0),
 (176896, 24591, 2),
 (51, 27830, 3),
 (51, 4431, 2),
 (51, 26685, 2),
 (51, 37916, 2),
 (195952, 38999, 1),
 (195952, 4245, 1),
 (195952, 31523, 1),
 (195952, 18901, 1),
 (195952, 20425, 1),
 (195952, 33651, 1),
 (195952, 18008, 1),
 (195952, 8960, 1),
 (195952, 39760, 1),
 (195952, 34483, 1),
 (195952, 18494, 1),
 (195952, 18232, 1),
 (51812, 34856, 1),
 (51812, 3180, 0),
 (51812, 36180, 1),
 (51812, 7119, 1),
 (51812, 7124, 0),
 (41868, 20394, 2),
 (41868, 7031, 3),
 (41868, 18948, 1),
 (41868, 26439, 2),
 (41868, 17534, 3),
 (40238, 17491, 3),
 (40238, 14703, 2),
 (40238, 9469, 2),
 (40238, 10040, 2),
 (40238, 28064, 1),
 (40238, 23957, 1),
 (40238, 37292, 1),
 (40238, 12358, 1),
 (158311, 6572, 1),
 (158311, 1214, 1),
 (158311, 11630, 1),
 (158311, 18559, 1),
 (67039, 10688, 3),
 (67039, 17967, 3),
 (67039, 24835, 2),
 (67039, 32523, 2),
 (67039, 21085, 2),
 (145497, 16500, 2),
 (145497, 24943, 2),
 (145497, 20677, 2),
 (145497, 30852, 3),
 (145497, 32120, 2),
 (95034, 12335, 2),
 (95034, 35165, 3),
 (95034, 32017, 2),
 (95034, 15247, 3),
 (95034, 10873, 3),
 (95034, 24045, 2),
 (95034, 15806, 2),
 (14063, 38512, 2),
 (14063, 24502, 3),
 (14063, 17997, 2),
 (14063, 15542, 2),
 (14063, 27705, 3),
 (14063, 17701, 2),
 (14063, 86, 2),
 (14063, 4548, 2),
 (14063, 16666, 3),
 (14063, 21929, 2),
 (14063, 35860, 2),
 (14063, 32464, 3),
 (167751, 13624, 2),
 (167751, 11344, 2),
 (167751, 3869, 3),
 (167751, 10471, 2),
 (124009, 21873, 1),
 (124009, 8071, 1),
 (124009, 3533, 1),
 (124009, 39439, 1),
 (171486, 9706, 2),
 (171486, 10955, 3),
 (171486, 17195, 2),
 (171486, 18161, 2),
 (171486, 33111, 2),
 (116672, 3897, 2),
 (116672, 30817, 2),
 (116672, 10410, 2),
 (116672, 2207, 3),
 (111313, 1934, 2),
 (111313, 10158, 2),
 (111313, 31124, 2),
 (111313, 6610, 2),
 (53612, 5544, 2),
 (53612, 11372, 1),
 (53612, 14672, 2),
 (53612, 37602, 2),
 (10816, 3628, 3),
 (10816, 6198, 2),
 (10816, 37472, 2),
 (10816, 37635, 2),
 (26710, 2018, 3),
 (26710, 8272, 2),
 (26710, 10404, 0),
 (26710, 3391, 2),
 (26710, 24033, 0),
 (26710, 23367, 0),
 (26710, 19354, 3),
 (26710, 8934, 2),
 (166420, 32980, 0),
 (166420, 39134, 0),
 (166420, 12315, 0),
 (166420, 25301, 1),
 (166420, 29692, 0),
 (166420, 19834, 0),
 (166420, 4650, 0),
 (166420, 3387, 0),
 (84055, 28056, 2),
 (84055, 8119, 2),
 (84055, 2743, 2),
 (84055, 8724, 2),
 (84055, 30905, 3),
 (140388, 15331, 2),
 (140388, 34706, 3),
 (140388, 3710, 3),
 (140388, 34437, 2),
 (140388, 30201, 2),
 (102700, 24062, 2),
 (102700, 28669, 2),
 (102700, 14524, 3),
 (102700, 12601, 3),
 (122409, 18360, 2),
 (122409, 3490, 2),
 (122409, 33469, 3),
 (122409, 32352, 2),
 (122409, 6780, 2),
 (122409, 184, 3),
 (120215, 8086, 2),
 (120215, 27516, 3),
 (120215, 7622, 2),
 (120215, 29707, 3),
 (120215, 21351, 2),
 (87450, 27562, 0),
 (87450, 33262, 1),
 (87450, 16495, 0),
 (87450, 12064, 0),
 (169309, 23089, 2),
 (169309, 17885, 0),
 (169309, 33135, 3),
 (169309, 20641, 0),
 (169309, 5944, 0),
 (169309, 16068, 2),
 (169309, 5772, 3),
 (114592, 16713, 2),
 (114592, 2548, 2),
 (114592, 28572, 2),
 (114592, 12511, 2),
 (2038, 12348, 2),
 (2038, 14268, 1),
 (75667, 16409, 1),
 (75667, 17098, 2),
 (75667, 12643, 1),
 (66084, 32558, 1),
 (66084, 27906, 1),
 (66084, 36776, 1),
 (66084, 1784, 1),
 (66084, 16729, 1),
 (66084, 31889, 1),
 (66084, 36381, 1),
 (66084, 27192, 1),
 (66084, 5422, 1),
 (66084, 13223, 1),
 (66084, 20522, 1),
 (66084, 10004, 1),
 (66084, 10122, 1),
 (66084, 28688, 1),
 (102777, 17330, 3),
 (102777, 37020, 2),
 (102777, 1989, 2),
 (158403, 11622, 1),
 (158403, 23201, 1),
 (158403, 28194, 1),
 (135574, 23452, 3),
 (135574, 25541, 2),
 (135574, 36142, 2),
 (135574, 12723, 2),
 (135574, 37037, 3),
 (135574, 20082, 2),
 (135574, 2005, 2),
 (120344, 20404, 2),
 (120344, 701, 3),
 (120344, 19096, 1),
 (120344, 29488, 1),
 (120344, 8504, 1),
 (59774, 14912, 1),
 (59774, 28576, 1),
 (59774, 37548, 1),
 (59774, 223, 1),
 (181917, 29364, 2),
 (181917, 11187, 3),
 (181917, 26930, 2),
 (181917, 21165, 2),
 (83231, 6483, 3),
 (83231, 10838, 2),
 (83231, 11535, 2),
 (83231, 31002, 2),
 (83231, 12933, 2),
 (83231, 30141, 2),
 (83231, 2002, 2),
 (156357, 36416, 1),
 (156357, 38184, 1),
 (156357, 8015, 1),
 (156357, 3303, 1),
 (156357, 2648, 1),
 (100677, 30998, 1),
 (100677, 13541, 2),
 (100677, 19201, 2),
 (100677, 15738, 2),
 (34144, 3419, 2),
 (34144, 32230, 1),
 (34144, 36058, 1),
 (34144, 24, 1),
 (34144, 7240, 1),
 (34144, 17402, 1),
 (34144, 4777, 1),
 (92955, 1161, 1),
 (92955, 35835, 2),
 (92955, 38864, 2),
 (92955, 21451, 3),
 (92955, 35305, 2),
 (92955, 10385, 2),
 (40395, 12169, 2),
 (40395, 6963, 1),
 (40395, 29691, 2),
 (40395, 31091, 2),
 (18589, 29993, 2),
 (18589, 39060, 3),
 (18589, 18082, 3),
 (18589, 25066, 0),
 (153126, 34210, 3),
 (153126, 16418, 2),
 (153126, 10400, 3),
 (153126, 33581, 2),
 (153126, 35741, 2),
 (19814, 26125, 2),
 (19814, 4301, 2),
 (19814, 3305, 3),
 (19814, 31673, 2),
 (19814, 31166, 2),
 (142867, 15548, 1),
 (142867, 3352, 0),
 (142867, 38457, 0),
 (142867, 30455, 1),
 (142867, 8044, 1),
 (142867, 22699, 0),
 (142867, 920, 1),
 (172319, 7150, 2),
 (172319, 497, 2),
 (172319, 27655, 2),
 (172319, 21357, 2),
 (172319, 30986, 3),
 (132162, 21424, 2),
 (132162, 3510, 2),
 (132162, 29419, 2),
 (132162, 27700, 2),
 (132162, 4033, 2),
 (132162, 29214, 2),
 (132162, 31577, 2),
 (132162, 22457, 2),
 (132162, 10514, 2),
 (8137, 36037, 1),
 (8137, 6577, 2),
 (8137, 26919, 2),
 (8137, 3228, 2),
 (8137, 11484, 2),
 (8137, 14484, 2),
 (8137, 2955, 2),
 (8137, 37251, 2),
 (8137, 22176, 2),
 (8137, 28969, 2),
 (2365, 39667, 2),
 (2365, 4360, 2),
 (2365, 234, 2),
 (2365, 38829, 3),
 (2365, 19359, 2),
 (129006, 30418, 1),
 (129006, 16563, 1),
 (129006, 2080, 1),
 (129006, 34329, 1),
 (129006, 10326, 1),
 (129006, 27610, 1),
 (28771, 4769, 2),
 (28771, 15834, 2),
 (28771, 30088, 2),
 (28771, 1345, 3),
 (28771, 6968, 3),
 (32391, 4908, 2),
 (32391, 14166, 2),
 (32391, 16275, 1),
 (32391, 37325, 2),
 (32391, 6002, 1),
 (32391, 15946, 1),
 (189924, 27668, 3),
 (189924, 12182, 1),
 (189924, 34700, 1),
 (189924, 23418, 1),
 (141415, 16951, 2),
 (141415, 27539, 3),
 (141415, 14125, 2),
 (141415, 35640, 2),
 (141415, 13520, 3),
 (141415, 11989, 0),
 (141415, 2103, 3),
 (141415, 29758, 2),
 (141415, 23285, 2),
 (141415, 16784, 2),
 (141415, 15819, 2),
 (141415, 32425, 2),
 (141415, 27925, 2),
 (141415, 36722, 3),
 (141415, 36422, 2),
 (141415, 5793, 2),
 (141415, 26319, 2),
 (63579, 19422, 2),
 (63579, 8468, 2),
 (63579, 3904, 2),
 (63579, 19245, 2),
 (1690, 17344, 2),
 (1690, 27531, 3),
 (1690, 6048, 2),
 (1690, 4414, 1),
 (1690, 9252, 2),
 (1690, 39016, 0),
 (1690, 20323, 2),
 (1690, 23669, 2),
 (1690, 34787, 2),
 (1690, 31196, 2),
 (1690, 37839, 3),
 (1690, 7172, 2),
 (65964, 17571, 2),
 (65964, 28594, 2),
 (65964, 14897, 2),
 (65964, 31017, 2),
 (65964, 9873, 2),
 (65964, 28842, 3),
 (65964, 23730, 2),
 (65964, 24578, 2),
 (65964, 8218, 2),
 (65964, 26018, 3),
 (65964, 964, 2),
 (65964, 3448, 2),
 (65964, 17112, 3),
 (65964, 928, 3),
 (65964, 11628, 2),
 (40215, 34500, 2),
 (40215, 16694, 3),
 (40215, 13762, 2),
 (40215, 777, 3),
 (40215, 19505, 3),
 (40215, 10508, 2),
 (40215, 4264, 3),
 (155427, 3756, 3),
 (155427, 35978, 3),
 (155427, 15923, 1),
 (155427, 936, 2),
 (86205, 6084, 2),
 (86205, 6830, 3),
 (86205, 1554, 0),
 (86205, 27941, 0),
 (86205, 2941, 3),
 (86205, 8013, 0),
 (86205, 8455, 2),
 (86205, 23560, 0),
 (166394, 23435, 2),
 (166394, 25966, 1),
 (166394, 33770, 3),
 (166394, 33467, 1),
 (166394, 16023, 1),
 (166394, 26839, 1),
 (68943, 19119, 2),
 (68943, 14761, 2),
 (68943, 2621, 2),
 (112657, 24531, 1),
 (112657, 20507, 1),
 (112657, 21048, 1),
 (112657, 23281, 1),
 (112657, 13991, 1),
 (112657, 32934, 2),
 (103896, 13857, 1),
 (103896, 691, 0),
 (103896, 12889, 0),
 (103896, 27464, 0),
 (118126, 21376, 0),
 (118126, 35456, 0),
 (118126, 16797, 0),
 (118126, 36770, 0),
 (118126, 9624, 2),
 (118126, 14140, 3),
 (118126, 14122, 3),
 (118126, 8295, 1),
 (118126, 296, 2),
 (118126, 2550, 2),
 (118126, 29136, 3),
 (118126, 39555, 2),
 (118126, 1597, 0),
 (118126, 8917, 0),
 (118126, 16748, 0),
 (118126, 9777, 0),
 (118126, 21285, 0),
 (118126, 27029, 2),
 (118126, 33037, 0),
 (192262, 21748, 1),
 (192262, 21114, 1),
 (192262, 20793, 1),
 (192262, 30565, 1),
 (131605, 18899, 3),
 (131605, 18807, 2),
 (131605, 28086, 2),
 (131605, 36871, 2),
 (131605, 11482, 2),
 (131605, 9698, 3),
 (22148, 3424, 2),
 (22148, 5949, 3),
 (22148, 7680, 2),
 (22148, 7585, 3),
 (22148, 9003, 2),
 (22148, 18027, 1),
 (48365, 4942, 2),
 (48365, 29140, 3),
 (48365, 3667, 2),
 (48365, 37524, 2),
 (30238, 13428, 0),
 (30238, 3067, 0),
 (30238, 15550, 0),
 (30238, 28010, 0),
 (30238, 11819, 2),
 (30238, 33476, 3),
 (30238, 38713, 0),
 (30238, 26169, 0),
 (114276, 38191, 1),
 (114276, 8361, 1),
 (114276, 13656, 1),
 (114276, 21261, 1),
 (114276, 14760, 1),
 (177269, 25056, 0),
 (177269, 19153, 0),
 (177269, 20301, 2),
 (177269, 33684, 3),
 (116072, 21459, 1),
 (116072, 19320, 1),
 (116072, 29605, 1),
 (91097, 17858, 2),
 (91097, 12613, 2),
 (91097, 36742, 2),
 (91097, 13417, 2),
 (91097, 26987, 2),
 (91097, 11356, 2),
 (91097, 9614, 3),
 (91097, 29130, 2),
 (91097, 30842, 2),
 (91097, 31353, 2),
 (91097, 9908, 2),
 (91097, 36963, 2),
 (91097, 13682, 3),
 (68196, 15903, 3),
 (68196, 813, 2),
 (68196, 19549, 2),
 (68196, 28236, 2),
 (68196, 29592, 3),
 (68196, 22898, 3),
 (68196, 31908, 3),
 (68196, 3849, 2),
 (68196, 2022, 2),
 (68196, 12954, 2),
 (68196, 14148, 2),
 (68196, 2824, 2),
 (68196, 24220, 3),
 (68196, 34969, 3),
 (68196, 29708, 2),
 (70490, 23972, 2),
 (70490, 23018, 2),
 (70490, 5841, 2),
 (70490, 25499, 3),
 (70490, 11711, 2),
 (52817, 9526, 0),
 (52817, 21294, 2),
 (52817, 15679, 0),
 (52817, 21801, 0),
 (52817, 8123, 0),
 (52817, 39827, 2),
 (52817, 15613, 0),
 (92209, 39394, 1),
 (92209, 20652, 1),
 (92209, 35124, 1),
 (92209, 38365, 1),
 (92209, 22272, 1),
 (92209, 22176, 1),
 (92209, 35997, 1),
 (92209, 13309, 1),
 (92209, 39242, 1),
 (92209, 6605, 1),
 (92209, 308, 1),
 (92209, 21621, 1),
 (92209, 25312, 1),
 (95247, 11448, 2),
 (95247, 22731, 2),
 (95247, 30848, 2),
 (95247, 37360, 2),
 (95247, 31992, 2),
 (120394, 23734, 0),
 (120394, 25515, 2),
 (120394, 12012, 2),
 (120394, 31292, 2),
 (120394, 33431, 2),
 (120394, 29052, 2),
 (120394, 35768, 3),
 (120394, 28486, 0),
 (120394, 5549, 2),
 (120394, 25250, 2),
 (120394, 16307, 2),
 (120394, 23368, 2),
 (120394, 16127, 2),
 (181064, 39702, 2),
 (181064, 29224, 2),
 (181064, 29929, 2),
 (181064, 26816, 3),
 (181064, 17859, 3),
 (181064, 20615, 2),
 (181064, 33994, 2),
 (181064, 3107, 2),
 (181064, 34402, 2),
 (181064, 29522, 3),
 (181064, 9858, 2),
 (181064, 15386, 3),
 (181064, 23752, 2),
 (181064, 19310, 2),
 (141826, 9391, 2),
 (141826, 6798, 1),
 (141826, 1826, 2),
 (141826, 37942, 2),
 (141826, 22967, 3),
 (141826, 24123, 1),
 (141826, 9062, 3),
 (141826, 30405, 1),
 (141826, 9818, 2),
 (92868, 38274, 3),
 (92868, 5058, 1),
 (92868, 752, 2),
 (92868, 36456, 1),
 (92868, 35065, 1),
 (92868, 2181, 1),
 (92868, 15492, 1),
 (92868, 13387, 2),
 (92868, 14190, 3),
 (92868, 39403, 1),
 (92868, 12654, 2),
 (92868, 22082, 2),
 (60726, 26365, 3),
 (60726, 17849, 2),
 (60726, 7085, 2),
 (60726, 27328, 2),
 (60726, 28099, 3),
 (60726, 13473, 2),
 (60726, 8569, 3),
 (60726, 21317, 2),
 (60726, 38841, 2),
 (63239, 13841, 3),
 (63239, 29095, 2),
 (63239, 2859, 3),
 (63239, 11900, 2),
 (63239, 35838, 2),
 (63239, 34266, 2),
 (165425, 18998, 2),
 (165425, 32722, 1),
 (165425, 38871, 1),
 (165425, 20886, 1),
 (165425, 2218, 2),
 (165425, 26594, 2),
 (192406, 16212, 2),
 (192406, 36979, 2),
 (192406, 35037, 2),
 (192406, 24411, 2),

In [327]:
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

NameError: name 'start_time' is not defined

In [350]:
neg_samples_df=pd.DataFrame(final,columns=['user_id','item_id','context_feature_id'])
neg_samples_df.shape

(892371, 3)

In [351]:
neg_samples_df['flag']=0
df_train['flag']=1

In [352]:
df_train_ns=pd.concat([df_train[['user_id','item_id','context_feature_id','flag']],neg_samples_df])

In [353]:
df_train_ns

        user_id  item_id  context_feature_id  flag
0          9974    27644                   2     1
1         80354    28735                   2     1
2        105125     1092                   1     1
3         47143    18484                   2     1
4         61416    10009                   1     1
...         ...      ...                 ...   ...
892366    80467    32082                   1     0
892367    22665    21360                   1     0
892368    57955    11675                   1     0
892369   131986    30990                   1     0
892370    35765    20653                   1     0

[1784742 rows x 4 columns]

In [354]:
df_train_ns.to_csv("/Users/surbhiprasad/Advanced_ML/Kaggle_Competition/kaggle_2/total_train_1ns_seed3_new_2.csv",index=False)

In [ ]:
max(df_train_ns['item_id'])

In [ ]:
neg_samples_df.shape,(df_train.shape[0]*2)